# Generated by Django 3.1.3 on 2020-11-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('text', models.CharField(max_length=256)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.board')),
            ],
            options={
                'unique_together': {('board', 'position')},
            },
        ),
    ]
