# Generated by Django 3.1.3 on 2020-12-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='tooltip',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
