# Generated by Django 3.1.3 on 2020-12-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_square_tooltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='xml_id',
            field=models.SlugField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
