# Generated by Django 3.1.3 on 2020-12-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_playerboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='seed',
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name='playerboard',
            name='squares',
            field=models.CharField(default='0000000000000000000000000', max_length=25),
        ),
    ]
