# Generated by Django 3.1.3 on 2020-12-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201201_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerboard',
            name='disconnected_at',
            field=models.DateTimeField(null=True),
        ),
    ]
