# Generated by Django 3.1.4 on 2021-02-14 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.SlugField(max_length=128, unique=True)),
                ('seed', models.SlugField(max_length=128)),
                ('difficulty', models.IntegerField(default=2)),
                ('forced_goals', models.CharField(default='', max_length=256)),
                ('obscured', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=128)),
                ('disconnected_at', models.DateTimeField(null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.board')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['y', 'x', 'z'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('tooltip', models.CharField(max_length=512)),
                ('xml_id', models.SlugField(max_length=256)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.board')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.position')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBoardMarking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField()),
                ('player_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.playerboard')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.space')),
            ],
        ),
        migrations.AddField(
            model_name='playerboard',
            name='markings',
            field=models.ManyToManyField(through='backend.PlayerBoardMarking', to='backend.Space'),
        ),
        migrations.AlterUniqueTogether(
            name='playerboard',
            unique_together={('board', 'player_name')},
        ),
    ]
