# Generated by Django 3.1.4 on 2020-12-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.SlugField(max_length=128, unique=True)),
                ('seed', models.SlugField(max_length=128)),
                ('difficulty', models.IntegerField()),
                ('obscured', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('text', models.CharField(max_length=256)),
                ('tooltip', models.CharField(max_length=512)),
                ('xml_id', models.SlugField(max_length=256)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.board')),
            ],
            options={
                'unique_together': {('board', 'position')},
            },
        ),
        migrations.CreateModel(
            name='PlayerBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=128)),
                ('squares', models.CharField(default='0000000000000000000000000', max_length=25)),
                ('disconnected_at', models.DateTimeField(null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.board')),
            ],
            options={
                'unique_together': {('board', 'player_name')},
            },
        ),
    ]
