# Generated by Django 3.1.6 on 2021-02-16 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['y', 'x']},
        ),
        migrations.RemoveField(
            model_name='position',
            name='z',
        ),
    ]
