# Generated by Django 3.1.6 on 2021-02-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_z_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='shape',
            field=models.CharField(choices=[('square', 'Square'), ('hexagon', 'Hexagon')], default='square', max_length=16),
            preserve_default=False,
        ),
    ]
