# Generated by Django 3.1.6 on 2021-02-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_board_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='board',
            name='forced_goals',
        ),
        migrations.RemoveField(
            model_name='board',
            name='seed',
        ),
    ]
