# Generated by Django 3.1.6 on 2021-02-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_board_creation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='win_detector',
            field=models.CharField(choices=[('bingo_standard', 'Standard Bingo rules')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='playerboardmarking',
            name='color',
            field=models.IntegerField(choices=[(0, 'Unmarked'), (1, 'Complete'), (2, 'Reverted'), (3, 'Invalidated'), (4, 'Not Invalidated')]),
        ),
    ]
