# Generated by Django 3.1.6 on 2021-03-13 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_win_detector_snake'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=1024)),
                ('player_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.playerboard')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.space')),
            ],
        ),
    ]
