# Generated by Django 3.1.6 on 2021-03-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_automarker'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerboardmarking',
            name='covert_marked',
            field=models.BooleanField(default=False),
        ),
    ]
