# Generated by Django 3.1.6 on 2021-03-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_playerboardmarking_covert_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerboardmarking',
            name='auto_marker_client_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='playerboard',
            name='player_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='AutoMarker',
        ),
    ]
