# Generated by Django 3.1.6 on 2021-04-09 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_single_client_automark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='text',
        ),
        migrations.RemoveField(
            model_name='space',
            name='tooltip',
        ),
        migrations.RemoveField(
            model_name='space',
            name='xml_id',
        ),
        migrations.AddField(
            model_name='space',
            name='goal_id',
            field=models.SlugField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SetVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.IntegerField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.space')),
            ],
            options={
                'unique_together': {('space', 'name')},
            },
        ),
    ]
