# Generated by Django 3.1.6 on 2021-05-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_marking_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerboardmarking',
            name='marked_by_player',
            field=models.BooleanField(default=False),
        ),
    ]
